# fly.toml app configuration file generated for marvel-dc-ultimate-guide-backend on 2025-04-02T17:48:52+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'marvel-dc-ultimate-guide-backend'
primary_region = 'mad'
console_command = '/code/manage.py shell'

[processes]
  app = "gunicorn marvel_dc_ultimate_guide.wsgi:application --bind 0.0.0.0:8080"

[build]

[deploy]
  release_command = 'python manage.py migrate --noinput'

[env]
  DATABASE_URL = 'postgres://marvel_dc_ultimate_guide_backend:DUI5CDXwhJNCLFH@marvel-dc-postgres.internal:5432/marvel_dc_ultimate_guide_backend?sslmode=require'
  DJANGO_SETTINGS_MODULE = 'marvel_dc_ultimate_guide.settings'
  PORT = '8000'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[services]]
  processes = ["app"]
  internal_port = 8080
  protocol = "tcp"

  [[services.ports]]
    port = 80
    handlers = ['http']

  [[services.ports]]
    port = 443
    handlers = ['tls', 'http']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1

[[statics]]
  guest_path = '/code/static'
  url_prefix = '/static/'
